Table displayed in full view
LogeshKandasamy/Tutorials pull request #25
Opened 2022-11-29 09:46 UTC by kalaivanidkpm

table view displayed in full width with x-axis scroll bar.

2022-11-29 10:07 UTC, LogeshKandasamy requested changes
Implement the other columns in Search

2022-12-01 04:12 UTC, LogeshKandasamy commented on Reactjs/src/components/customer/PaginationDatas.js
> +                    {/* <li key={pgNumber} className="page-item">
Remove this code if not required

2022-12-02 06:05 UTC, kalaivanidkpm commented on Reactjs/src/components/customer/PaginationDatas.js
> +                    {/* <li key={pgNumber} className="page-item">
removed this code

2022-12-02 08:20 UTC, LogeshKandasamy approved these changes

2022-12-02 08:20 UTC, merged