Product create
LogeshKandasamy/Tutorials pull request #28
Opened 2023-01-02 05:34 UTC by kalaivanidkpm

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +          formValid:this.state.reed && this.state.pick
warp and wept and width is not added in the formValid

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +                    fieldValidationErrors.loomType = " LoomType is required. ";
Can you move the string  " LoomType is required. "; to Constants.js

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +        console.log("Name : ",targetName);
remove the console used for debg purpose

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +        rows[idp]={[targetName]:targetBValue};
targetBValue spell check

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +            console.log(rows)
remove the console

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +        const tableItem={ reed:"",pick:"",warp:"",wept:"",width:""};
loomtype is not added in the table row

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +      if (this.state.formErrors.reed.length != null &&
warp, wept and width check is missing

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +            const url= "https://vab0g55bof.execute-api.ap-southeast-1.amazonaws.com/nonprod/product";
url should be  in the API Service.js

2023-01-02 05:50 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +            axios.post(url,{productData},{headers:curHeaders})
send the post data to APIService

2023-01-02 06:02 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +        rows[idp]={[targetName]:targetBValue};
Corrected.

2023-01-02 06:02 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +        console.log("Name : ",targetName);
ok sir, Removed.

2023-01-02 06:03 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +          formValid:this.state.reed && this.state.pick
warp, width,wept added in formvalid

2023-01-02 06:03 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +            console.log(rows)
removed.

2023-01-02 06:05 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +        const tableItem={ reed:"",pick:"",warp:"",wept:"",width:""};
loomtype added.

2023-01-02 06:07 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +      if (this.state.formErrors.reed.length != null &&
checked warp wept and width.

2023-01-02 06:31 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +            axios.post(url,{productData},{headers:curHeaders})
data send to the API services

2023-01-02 06:32 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +            const url= "https://vab0g55bof.execute-api.ap-southeast-1.amazonaws.com/nonprod/product";
get the URL in API services

2023-01-02 07:51 UTC, LogeshKandasamy requested changes

2023-01-02 07:51 UTC, LogeshKandasamy commented on Reactjs/src/components/product/ProductCreate.js
> +            APIService.getProductCreate({productData})
get is used for read the data frm backend , 

Correct the method name

2023-01-02 07:51 UTC, LogeshKandasamy commented on Reactjs/src/service/APIService.js
> +const PRODUCT_REST_API_URL = 'https://vab0g55bof.execute-api.ap-southeast-1.amazonaws.com/nonprod/product';
Customer and product url is almost same 

last portion varies /customer , / product

modify more simpler way

2023-01-02 07:51 UTC, LogeshKandasamy commented on Reactjs/src/service/APIService.js
> +    'Content-Type': 'eg'
Content-Type is 'eg' 

invalid content type

2023-01-02 07:53 UTC, kalaivanidkpm commented on Reactjs/src/service/APIService.js
> +    'Content-Type': 'eg'
Removed

2023-01-02 08:00 UTC, kalaivanidkpm commented on Reactjs/src/service/APIService.js
> +const PRODUCT_REST_API_URL = 'https://vab0g55bof.execute-api.ap-southeast-1.amazonaws.com/nonprod/product';
URl modified and checked  for both Customer and Product.

2023-01-02 08:07 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +            APIService.getProductCreate({productData})
name changed.

2023-01-03 08:05 UTC, kalaivanidkpm commented on Reactjs/src/components/product/ProductCreate.js
> +                    fieldValidationErrors.loomType = " LoomType is required. ";
MODIFIED

2023-01-04 04:57 UTC, LogeshKandasamy approved these changes

2023-01-04 04:57 UTC, merged